# constants.py
SCREEN_WIDTH = 320
SCREEN_HEIGHT = 240
BASE_Y = 212
CITY_Y = 212
METEOR_SPEED_MIN = 1
METEOR_SPEED_MAX = 2
EXPLOSION_RADIUS_MAX = 30
EXPLOSION_DURATION = 20
MISSILE_SPEED = 5
GRAND_Y = 220

# Additional constants
METEOR_RADIUS = 1
MISSILE_RADIUS = 1
MISSILE_COLOR = 10
EXPLOSION_INITIAL_RADIUS = 1
EXPLOSION_RADIUS_INCREMENT = 0.5
EXPLOSION_DURATION_DECREMENT = 1
EXPLOSION_COLOR = 8
METEOR_SPAWN_INTERVAL = 30
METEOR_SPAWN_COUNT = 1
METEOR_ANGLE_RANGE = 45
METEOR_INITIAL_Y = 0
METEOR_OFFSCREEN_OFFSET = 5
GROUND_HIT_DISTANCE = 16
COLLISION_DISTANCE = 3

# Image resource constants
BASE_IMG_X = 8
BASE_IMG_Y = 0
BASE_IMG_WIDTH = 16
BASE_IMG_HEIGHT = 8
CITY_IMG_X = 0
CITY_IMG_Y = 8
CITY_IMG_WIDTH = 16
CITY_IMG_HEIGHT = 8

# Collision offset
CITY_COLLISION_OFFSET = 4
BASE_COLLISION_OFFSET = 4

# Base and City positions
BASE_X_POSITIONS = [20, 160, 300]
CITY_X_POSITIONS = [60, 90, 120, 200, 230, 260]

# Colors
GROUND_COLOR = 2
SCORE_TEXT_COLOR = 7
GAME_OVER_TEXT_COLOR = 8
RETRY_TEXT_COLOR = 7
METEOR_COLOR = 14

# Text positions
SCORE_TEXT_X = 5
SCORE_TEXT_Y = 5
GAME_OVER_TEXT_X_OFFSET = 40
GAME_OVER_TEXT_Y_OFFSET = 10
RETRY_TEXT_X_OFFSET = 60
RETRY_TEXT_Y_OFFSET = 5

# UFO constants
UFO_SPEED = 2
UFO_WIDTH = 16
UFO_HEIGHT = 8
UFO_IMG_X = 16
UFO_IMG_Y = 8
UFO_FLYING_HEIGHT_LIMIT = 100
UFO_SPAWN_INTERVAL = 240