# 隕石
METEOR_SPEED_MIN = 1
METEOR_SPEED_MAX = 2
METEOR_RADIUS = 1
METEOR_SPAWN_INTERVAL = 30
METEOR_SPAWN_COUNT = 1
METEOR_ANGLE_RANGE = 45
METEOR_INITIAL_Y = 0
METEOR_OFFSCREEN_OFFSET = 5

# ミサイル
MISSILE_SPEED = 5
MISSILE_RADIUS = 1

# 爆発
EXPLOSION_RADIUS_MAX = 30
EXPLOSION_DURATION = 20
EXPLOSION_INITIAL_RADIUS = 1
EXPLOSION_RADIUS_INCREMENT = 0.5
EXPLOSION_DURATION_DECREMENT = 1

# UFO
UFO_SPEED = 2
UFO_WIDTH = 16
UFO_HEIGHT = 8
UFO_FLYING_HEIGHT_LIMIT = 100
UFO_SPAWN_INTERVAL = 240

# 衝突判定
COLLISION_DISTANCE = 3
CITY_COLLISION_OFFSET = 4
BASE_COLLISION_OFFSET = 4
GROUND_HIT_DISTANCE = 16

# 配置
BASE_X_POSITIONS = [20, 160, 300]
CITY_X_POSITIONS = [60, 90, 120, 200, 230, 260]

# Y座標
BASE_Y = 212
CITY_Y = 212
