# Base画像
BASE_IMG_X = 8
BASE_IMG_Y = 0
BASE_IMG_WIDTH = 16
BASE_IMG_HEIGHT = 8

# City画像
CITY_IMG_X = 0
CITY_IMG_Y = 8
CITY_IMG_WIDTH = 16
CITY_IMG_HEIGHT = 8

# UFO画像
UFO_IMG_X = 16
UFO_IMG_Y = 8
UFO_IMG_WIDTH = 16
UFO_IMG_HEIGHT = 8

# Missile画像
MISSILE_IMG_X = 0
MISSILE_IMG_Y = 16
MISSILE_IMG_WIDTH = 4
MISSILE_IMG_HEIGHT = 8

# Meteor画像
METEOR_IMG_X = 4
METEOR_IMG_Y = 16
METEOR_IMG_WIDTH = 8
METEOR_IMG_HEIGHT = 8

# Explosion画像
EXPLOSION_IMG_X = 12
EXPLOSION_IMG_Y = 16
EXPLOSION_IMG_WIDTH = 16
EXPLOSION_IMG_HEIGHT = 16
