# 画面サイズ
SCREEN_WIDTH = 320
SCREEN_HEIGHT = 240
GRAND_Y = 220

# 色
GROUND_COLOR = 2
SCORE_TEXT_COLOR = 7
GAME_OVER_TEXT_COLOR = 8
RETRY_TEXT_COLOR = 7
METEOR_COLOR = 14
MISSILE_COLOR = 10
EXPLOSION_COLOR = 8

# テキスト位置
SCORE_TEXT_X = 5
SCORE_TEXT_Y = 5
GAME_OVER_TEXT_X_OFFSET = 40
GAME_OVER_TEXT_Y_OFFSET = 10
RETRY_TEXT_X_OFFSET = 60
RETRY_TEXT_Y_OFFSET = 5
